### ISSUE TITLE
Error Loading script

### ISSUE THREAD

**Issue by Arkanosmalkier** [xrpgame/xyz_plot_script#1]
the following errors come up when attempting to load Stable Diffusion with your xyz plot script:
Error loading script: vue.min.js
Traceback (most recent call last):
  File "C:\dif\stable-diffusion-webui-master\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "C:\dif\stable-diffusion-webui-master\scripts\vue.min.js", line 1
    /*!
    ^
SyntaxError: invalid syntax

Error loading script: xyz_grid.py
Traceback (most recent call last):
  File "C:\dif\stable-diffusion-webui-master\modules\scripts.py", line 71, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\dif\stable-diffusion-webui-master\scripts\xyz_grid.py", line 16, in <module>
    from modules.hypernetworks import hypernetwork
ModuleNotFoundError: No module named 'modules.hypernetworks'

Error loading script: xyz_grid.template.html
Traceback (most recent call last):
  File "C:\dif\stable-diffusion-webui-master\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "C:\dif\stable-diffusion-webui-master\scripts\xyz_grid.template.html", line 10
    --label-col-width: 220px;
                         ^
SyntaxError: invalid decimal literal

**Comment by zer0TF** [comment]
So, there are two issues here:

1. The SD WebUI loads *any* file as a Python file and tries to run it. This includes the HTML template file. I'm working on a PR to fix this. **This error is safe to ignore and your WebUI should still work.**
2. You need to update your WebUI to the latest version (`git pull`), to fix this error: `ModuleNotFoundError: No module named 'modules.hypernetworks'`

I'll leave this open for now until the script loading is fixed.

**Comment by zer0TF** [comment]
This should be resolved if you pull the latest version of AUTOMATIC1111's WebUI - issue fixed in this commit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6f7b7a3dcdc471ebe63baa8a7731952557859c5b

Closing.
