### ISSUE TITLE
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (F:\stable-diffusion-webui\modules\processing.py)

### ISSUE THREAD

**Issue by ghost** [xrpgame/xyz_plot_script#10]
```
venv "F:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: b5050ad2071644f7b4c99660dc66a8a95136102f
Installing requirements for Web UI

Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 40f81123b99492799d924b8c8816564ef6e8fa9f
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Transformers version is 4.21.0.

Launching Web UI with arguments: --deepdanbooru --autolaunch --xformers
Error loading script: xyz_grid.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\stable-diffusion-webui\scripts\xyz_grid.py", line 17, in <module>
    from modules.processing import StableDiffusionProcessingTxt2Img, process_images, get_correct_sampler
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (F:\stable-diffusion-webui\modules\processing.py)
```

**Comment by zer0TF** [comment]
Resolved with commit https://github.com/xrpgame/xyz_plot_script/commit/45db5dab7e56d0505289353f4c09620b3c7a88d2.
